version: '3'
services:
    database:
        image: mongo
        ports:
            - '27037:27017'
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
        volumes:
            - ./database:/data/db
    frontend:
        build: frontend
        environment:
            - REACT_APP_HOST=localhost
            - REACT_APP_PORT=5000
        ports:
            - '3000:3000'
        volumes:
            - /app/node_modules
            - ./frontend:/app
        depends_on:
            - backend
    backend:
        build: backend
        ports:
            - '5000:5000'
        environment:
            - PORT=5000
            - MONGO_LOCAL_PORT=27017
            - MONGO_HOST=database
            - MONGO_DB=bakery2
            - JWT_SECRET=bakery-secret
            - JWT_EXPIRE=1d
        volumes:
            - /app/node_modules
            - ./backend:/app
        depends_on:
            database:
                condition: service_healthy
    api-documentation:
        build: api-documentation
        ports:
            - '4000:4000'
        volumes:
            - /app/node_modules
            - ./backend:/app
